### ISSUE TITLE
This is fantastic! Keep up the good work

### ISSUE THREAD

**Issue by mardukbp** [kainjow/Glypha#1]
I did not find this repo by chance. I was actually looking for a cross-platform port of Glypha. I played it for years back in the day of 68k processors. Now I am a Linux user and I would love to play it again. I have no experience with C++ or game programming, but at least I want to contribute by cheering this effort.

**Comment by kainjow** [comment]
If you install Qt you should be able to build the Qt version by running `qmake Glypha.pro` from the qt directory (going off of memory here). I believe a sound player implementation is missing for Qt though, but graphics should work. I've only ever tested in virtual machines though.

**Comment by mardukbp** [comment]
It works great! Thank you! If you are using Qt 4, there is the [Phonon multimedia framework](http://doc.qt.io/qt-4.8/phonon-overview.html). For Qt 5, there is [Qt Multimedia](http://doc.qt.io/qt-5/audiooverview.html). I miss the sound of the thunders!

**Comment by Haifen** [comment]
I would strongly recommend using a more cross-platform-friendly audio framework than Phonon.  sdl/sdl2 doesn't directly support Phonon, but they support direct output to ALSA or PulseAudio, both of which can route to Phonon/Jack/etc, as well as support either DirectSound or CoreAudio.  It means an extra dependency, but it also means not rewriting the audio interface layer repeatedly to support more than a single platform.

**Comment by kainjow** [comment]
I have sample working code now that uses Qt5 multimedia classes to play the sounds. Just need to incorporate that into the project.

@Haifen one of my original personal goals for this project was to use native libraries as much as possible, mostly as a learning experience (and also to ease compilation). For the Qt version I'd like to use Qt as much as possible.

BTW, for any other future googlers... if you get the "using null output device, none available" error, the Qt5 version may be too old in your distro's package manager. Try uninstalling Qt5 and install from Qt's website instead to get a more up-to-date version. Sounds like there were some bugs before 5.4.

**Comment by kainjow** [comment]
Qt(5) version should be fully functional now.
