### ISSUE TITLE
Got a buffer underflow!

### ISSUE THREAD

**Issue by mardukbp** [kainjow/Glypha#3]
I compiled Glypha on Ubuntu 16.04 with Qt 5.6 from the Qt website and after dying in combat this message appeared several times in the terminal. The UI was unresponsive and I had to kill the process.

**Comment by kainjow** [comment]
Was the audio working up until that point?

**Comment by mardukbp** [comment]
Yes. I heard the crunchy bones ;)

**Comment by kainjow** [comment]
Are you testing on real hardware, or virtualized?

**Comment by mardukbp** [comment]
Real hardware. I have both Intel graphics and an NVIDIA card.

**Comment by kainjow** [comment]
Ok, I'll try to reproduce. I'm also going to replace all the AIFF sounds with WAV, which play back natively in pretty much every OS, whereas AIFF do not, and require custom code. So with that I may be able to simplify how the Qt sounds play.

**Comment by mardukbp** [comment]
That sounds like a good idea (pun intended)!

**Comment by kainjow** [comment]
Ok, attempted a possible fix in bf3c1e6918d1235c6455110dab95d5d28c0eb78d. Can you try again. I only tested with my Mac though.

**Comment by mardukbp** [comment]
Now I could play longer, but the message appears every time I press an arrow key. So it seems to be harmless. Now Glypha crashed with "Stream error: Too large".

**Comment by kainjow** [comment]
I just tested under Ubuntu 18 with latest Qt (5.11.1) through Parallels Desktop Lite and played up to level 12 and didn't see any crash, except for one at the end after the high score dialog which is probably unrelated. Going to close.
