### ISSUE TITLE
Mac version requires a code signing profile I didn't have

### ISSUE THREAD

**Issue by fzzzy** [kainjow/Glypha#4]
I was able to compile and run by opening build_release/Glypha.xcodeproj in Xcode, going to the Project Build Settings tab, choosing the Glypha app target, searching for "signing", and changing Code Signing Identity to "Don't Code Sign". I also had to set the Code Signing Entitlements setting to an empty string. Then it works!

**Comment by kainjow** [comment]
Ah, yes currently its hard coded to use my code signing certificate. I'll set up a new Makefile target that builds without code signing.

**Comment by kainjow** [comment]
This should be fixed now in 7cdce394c79ec99c0d91896ccc3d36e26c280fed.

**Comment by fzzzy** [comment]
Works. Thanks!
