### ISSUE TITLE
Release requires macOS 10.14

### ISSUE THREAD

**Issue by MikeRich88** [kainjow/Glypha#5]
The release says, "for macOS 10.12+ or greater" but when I try to run it, I get an error: "You can’t use this version of the application “Glypha III.app” with this version of macOS. You have macOS 10.13.6. The application requires macOS 10.14 or later."

**Comment by kainjow** [comment]
Hmmm, that's odd. The plist has LSMinimumSystemVersion defined as 10.12.0...

if you Show Package Contents on the .app and drag the Glypha binary to Terminal, does it launch there?

**Comment by kainjow** [comment]
I think I fixed this. Can you test this build out? https://github.com/kainjow/Glypha/releases/tag/v2.0.1

**Comment by MikeRich88** [comment]
That build works great! Tested on a Mac Pro with 10.12.6 and a MacBook Air with 10.13.6.

I remember this game from the big orange Mac Programmers book that I got a long time ago (I've still got it, somewhere). It was a huge book that came with a CD-ROM, which featured a fully working and licensed version of CodeWarrior. The only caveat being that the PowerPC compiler was excluded, you could only build for 68K.

Only problem is that I was like 10 years old at the time, so C programming was a bit over my head. Had a lot of fun with the Glypha III game though.
