### ISSUE TITLE
Problem with bluetooth audio device

### ISSUE THREAD

**Issue by electronicsguy** [kainjow/Glypha#6]
Hi, 
 I built this on my Ubuntu (18.04) machine with qt5 and cmake 3.13.4. The game starts up, but I get the following errors in the terminal:

Audio format is not supported.
Can't load sound 0
Audio format is not supported.
Can't load sound 1
Audio format is not supported.
Can't load sound 2
Audio format is not supported.
Can't load sound 3
Audio format is not supported.
Can't load sound 12
Audio format is not supported.
Can't load sound 5
Audio format is not supported.
Can't load sound 6
Audio format is not supported.
Can't load sound 7
Audio format is not supported.
Can't load sound 8
Audio format is not supported.
Can't load sound 13
Audio format is not supported.
Can't load sound 9
Audio format is not supported.
Can't load sound 10
Audio format is not supported.
Can't load sound 4
Audio format is not supported.
Can't load sound 11
libpng warning: iCCP: known incorrect sRGB profile
using null output device, none available
START error occurred: OpenError
using null output device, none available
START error occurred: OpenError
using null output device, none available
START error occurred: OpenError
using null output device, none available
START error occurred: OpenError
using null output device, none available
START error occurred: OpenError
using null output device, none available
START error occurred: OpenError
using null output device, none available
START error occurred: OpenError

Any idea why? I can hear sound through my bluetooth speakers while playing youtube in the browser.

**Comment by kainjow** [comment]
Not sure why, sorry. I haven't been super happy with the Qt version, but not sure how else to do the Linux version.
