### ISSUE TITLE
Issue when compiling on macOS 10.14.6

### ISSUE THREAD

**Issue by eisnerguy1** [kainjow/Glypha#8]
So, I'm trying build the latest version andI I'm getting errors about halfway through:

eisnerguy1s-MacBook-Pro-7:Glypha-master eisnerguy1$ make game
mkdir -p build
cd build && cmake -DCMAKE_BUILD_TYPE=Release ..
-- The C compiler identification is AppleClang 10.0.1.10010046
-- The CXX compiler identification is AppleClang 10.0.1.10010046
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenGL: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework   
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/eisnerguy1/Desktop/slugman/_new/Glypha-master/build
cd build && cmake --build . --config Release
gmake[1]: Entering directory '/Users/eisnerguy1/Desktop/slugman/_new/Glypha-master/build'
gmake[2]: Entering directory '/Users/eisnerguy1/Desktop/slugman/_new/Glypha-master/build'
gmake[3]: Entering directory '/Users/eisnerguy1/Desktop/slugman/_new/Glypha-master/build'
Scanning dependencies of target bin-convert
gmake[3]: Leaving directory '/Users/eisnerguy1/Desktop/slugman/_new/Glypha-master/build'
gmake[3]: Entering directory '/Users/eisnerguy1/Desktop/slugman/_new/Glypha-master/build'
[  1%] Building C object CMakeFiles/bin-convert.dir/bin-convert.c.o
[  2%] Linking C executable bin-convert
gmake[3]: Leaving directory '/Users/eisnerguy1/Desktop/slugman/_new/Glypha-master/build'
[  2%] Built target bin-convert
gmake[3]: Entering directory '/Users/eisnerguy1/Desktop/slugman/_new/Glypha-master/build'
[  4%] Generating resources/walk_wav.cpp
[  5%] Generating resources/about_png.cpp
[  6%] Generating resources/background_png.cpp
[  8%] Generating resources/bird_wav.cpp
[  9%] Generating resources/bonus_wav.cpp
[ 10%] Generating resources/boom1_wav.cpp
[ 12%] Generating resources/boom2_wav.cpp
[ 13%] Generating resources/egg_png.cpp
[ 14%] Generating resources/enemyFly_png.cpp
[ 16%] Generating resources/enemyWalk_png.cpp
[ 17%] Generating resources/eye_png.cpp
[ 18%] Generating resources/flap2_wav.cpp
[ 20%] Generating resources/flap_wav.cpp
[ 21%] Generating resources/font11_fnt.cpp
[ 22%] Generating resources/font11_png.cpp
[ 24%] Generating resources/grate_wav.cpp
[ 25%] Generating resources/hand_png.cpp
[ 26%] Generating resources/help_png.cpp
[ 28%] Generating resources/lightning_wav.cpp
[ 29%] Generating resources/music_wav.cpp
[ 30%] Generating resources/numbers_png.cpp
[ 32%] Generating resources/obelisks_png.cpp
[ 33%] Generating resources/platforms_png.cpp
[ 34%] Generating resources/playerIdle_png.cpp
[ 36%] Generating resources/player_png.cpp
[ 37%] Generating resources/scrape2_wav.cpp
[ 38%] Generating resources/screech_wav.cpp
[ 40%] Generating resources/spawn_wav.cpp
[ 41%] Generating resources/splash_wav.cpp
[ 42%] Generating resources/torches_png.cpp
Scanning dependencies of target Glypha
gmake[3]: Leaving directory '/Users/eisnerguy1/Desktop/slugman/_new/Glypha-master/build'
gmake[3]: Entering directory '/Users/eisnerguy1/Desktop/slugman/_new/Glypha-master/build'
[ 44%] Building CXX object CMakeFiles/Glypha.dir/game/GLGame.cpp.o
[ 45%] Building CXX object CMakeFiles/Glypha.dir/game/GLImage.cpp.o
[ 46%] Building CXX object CMakeFiles/Glypha.dir/game/GLRect.cpp.o
[ 48%] Building CXX object CMakeFiles/Glypha.dir/game/GLRenderer.cpp.o
[ 49%] Building CXX object CMakeFiles/Glypha.dir/game/GLUtils.cpp.o
[ 50%] Building CXX object CMakeFiles/Glypha.dir/game/GLBufferReader.cpp.o
[ 52%] Building CXX object CMakeFiles/Glypha.dir/game/GLFont.cpp.o
[ 53%] Building CXX object CMakeFiles/Glypha.dir/game/GLPrefs.cpp.o
[ 54%] Building CXX object CMakeFiles/Glypha.dir/mac/main.mm.o
/Users/eisnerguy1/Desktop/slugman/_new/Glypha-master/mac/main.mm:322:1: error: 
      method possibly missing a [super prepareOpenGL] call
      [-Werror,-Wobjc-missing-super-calls]
}
^
/Users/eisnerguy1/Desktop/slugman/_new/Glypha-master/mac/main.mm:329:1: error: 
      method possibly missing a [super reshape] call
      [-Werror,-Wobjc-missing-super-calls]
}
^
2 errors generated.
gmake[3]: *** [CMakeFiles/Glypha.dir/build.make:340: CMakeFiles/Glypha.dir/mac/main.mm.o] Error 1
gmake[3]: Leaving directory '/Users/eisnerguy1/Desktop/slugman/_new/Glypha-master/build'
gmake[2]: *** [CMakeFiles/Makefile2:124: CMakeFiles/Glypha.dir/all] Error 2
gmake[2]: Leaving directory '/Users/eisnerguy1/Desktop/slugman/_new/Glypha-master/build'
gmake[1]: *** [Makefile:171: all] Error 2
gmake[1]: Leaving directory '/Users/eisnerguy1/Desktop/slugman/_new/Glypha-master/build'
make: *** [game] Error 2
eisnerguy1s-MacBook-Pro-7:Glypha-master eisnerguy1$

Is this easily fixable?  Thanks!

**Comment by kainjow** [comment]
Looks like it's a warning/error from a more recent Xcode version. I fixed it though. Thanks for reporting.
